---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("devtools")
#library('devtools')
#devtools::install_github("usa-npn/rnpn")

library('rnpn')
library(tidyverse)
library(stringr)
library(lubridate)
library(htmlTable)

```


```{r, get station list}
species_list <- npn_species()


site <- npn_stations()
#subset to only NEON
neonSites <- site[site$network_id==77,]
#split out site names
neonSites$siteID <- substr(neonSites$station_name, 1, 4)
#primary or phenocam?
neonSites$type <- sub(".*-", "", neonSites$station_name)

sitesOfInterest <- c("HARV", "ONAQ", "OSBS", "DSNY", "ABBY")
stationIDs <- neonSites$station_id[neonSites$siteID%in%sitesOfInterest]

```



```{r, download data from npn}
df_mag <- npn_download_magnitude_phenometrics(request_source='KatieJ',
                                          period_frequency = '7',
                                          years=c('2015', '2016', '2017', '2018', '2019'), 
                                          station_ids=c(35924)
                                          )


df_site <- npn_download_site_phenometrics(request_source='KatieJ',
                                          years=c('2013','2014', '2015', '2016', '2017', '2018','2019'), 
                                          station_ids=stationIDs
                                          )

```


```{r, subset and summarize}
df_site$sciName <- paste(df_site$genus, df_site$species, sep=' ')

for(i in 1:nrow(df_site)){ 
  df_site$siteName[i] <- neonSites$siteID[neonSites$station_id==df_site$site_id[i]]
  df_site$plotType[i] <- neonSites$type[neonSites$station_id==df_site$site_id[i]]
}

site_sub <- df_site%>%
  select(siteName, sciName, plotType, year=mean_first_yes_year,first_yes_sample_size, last_yes_sample_size, phenophase_description, mean_first_yes_doy, mean_last_yes_doy)

firstPhase <- site_sub%>%
  filter(phenophase_description%in%c('Breaking leaf buds', 'Breaking needle buds (conifers)', 'Emerging needles (pines)',
                                     'Initial growth (forbs)', 'Initial growth (grasses/sedges)', 'Young leaves (tree/shrub)') & year!=-9999)%>%
  arrange(siteName, sciName, year)

firstPhase$firstYesDate <- as.Date(firstPhase$mean_first_yes_doy, origin = as.Date(paste0(firstPhase$year, "-01-01"),tz = "UTC") - days(1), tz = "UTC") 
firstPhase$lastYesDate <- as.Date(firstPhase$mean_last_yes_doy, origin = as.Date(paste0(firstPhase$year, "-01-01"),tz = "UTC") - days(1), tz = "UTC") 



lastPhase <- site_sub%>%
  filter(phenophase_description%in%c('Leaves (forbs)', 'Leaves (grasses)', 'Leaves') )%>%
  select(-mean_first_yes_doy)%>%
  arrange(siteName, sciName, year)

lastPhase$lastYesDate <- as.Date(lastPhase$mean_last_yes_doy, origin = as.Date(paste0(lastPhase$year, "-01-01"),tz = "UTC") - days(1), tz = "UTC") 


# not printing date correctly
# print(xtable(firstPhase), type="html", file="firstPhase.html")
# 
# print(xtable(lastPhase), type="html", file="lastPhase.html")

write.csv(firstPhase, 'firstPhase.csv', row.names=FALSE)
write.csv(lastPhase, 'lastPhase.csv', row.names=FALSE)

```


```{r, plot}
df <- filter(firstPhase, siteName=='ABBY')
ggplot(df, aes(x=mean_first_yes_doy, fill=sciName)) +
  #y = first_yes_sample_size
  #ggplot(df, aes(x=dayOfYear, ..count.., fill=phenophaseIntensity, color=phenophaseIntensity)) +  
  #geom_density(position="stack")+  # stacks data vertically
  #geom_density(alpha=0.8)+  # sensitivity of the curves
  #ggtitle("Leaves and Increasing Leaf Size status - D03")+
  geom_bar()+  
  facet_wrap(~year) #, scale="free_y")#+ # places taxonID in separate windows
  #xlim(min(df$date)-15, max(df$date)+15) # x-axis scales by date

```
